name: LBANN GPU (CUDA)

on:
  push:
    branches: develop
  pull_request:
    branches: develop
  merge_group:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cuda: ['11.8']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libyaml-dev cmake lmod ninja-build
        python -m pip install --upgrade pip

    - name: Install CUDA ${{ matrix.cuda }}
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update
        sudo apt-get -y install cuda-toolkit-11-8

    - name: Restore cached Spack-built dependencies
      id: cache-spack
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.spack
          spack
        key: ${{ runner.os }}-cuda${{ matrix.cuda }}-spackdeps

    - name: Build and install LBANN dependencies
      if: steps.cache-spack.outputs.cache-hit != 'true'
      run: |
        source /usr/share/lmod/lmod/init/bash
        git clone -c feature.manyFiles=true https://github.com/spack/spack.git
        cd spack
        git checkout 73858df14dc3f0e701814c84bb8bd6b72f80a806 # Use a tried and true version of Spack
        cd ..
        source spack/share/spack/setup-env.sh
        spack external find cuda
        spack external find -p /usr/local/cuda cuda
        scripts/build_lbann.sh -d --dependencies-only -l ci -- +numpy +unit_tests +cuda cuda_arch=70

    - name: Cache Spack-built dependencies
      id: cache-spack-save
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.spack
          spack
        key: ${{ runner.os }}-cuda${{ matrix.cuda }}-spackdeps

    - name: Build LBANN
      run: |
        source /usr/share/lmod/lmod/init/bash
        source spack/share/spack/setup-env.sh
        scripts/build_lbann.sh -r -l ci --ci -- +numpy +unit_tests +cuda cuda_arch=70
